repos:
  - repo: https://github.com/keith/pre-commit-buildifier
    rev: 8.2.1
    hooks:
      - id: buildifier
      - id: buildifier-lint

  - repo: https://github.com/pre-commit/mirrors-clang-format
    rev: v21.1.1
    hooks:
      - id: clang-format
