load("//mojo:mojo_library.bzl", "mojo_library")

mojo_library(
    name = "inner",
    srcs = [
        "__init__.mojo",
    ],
    import_path = "..",
    # TODO: Mojo doesn't officially support this yet, re-enable when it does
    tags = ["manual"],
    visibility = ["//tests:__subpackages__"],
)
