name: Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  test:
    permissions:
      contents: read
    strategy:
      matrix:
        os:
          - macos-15
          - ubuntu-latest
        bazel:
          - 8.x
          - 9.x
          - latest
          - last_rc
          - last_green
      fail-fast: false
    runs-on: ${{ matrix.os }}
    env:
      USE_BAZEL_VERSION: ${{ matrix.bazel }}
    steps:
      - uses: actions/checkout@v4
      - name: Bazel Info
        run: |
          bazel version
          bazel info
      - name: CPU Info
        run: |
          lscpu || true
      - run: bazel test //...
      - name: Debug Session
        if: ${{ failure() }}
        uses: mxschmitt/action-tmate@53a5c23a925969671a6bb98ea70a4f650928ef93
        with:
          limit-access-to-actor: false
